package routers

/**
 *
 * @author Sika Kay
 * @date 26/02/18
 *
 */

import (
	"github.com/bitwiseTek/manageme-dev/manageme/api/common"
	"github.com/bitwiseTek/manageme-dev/manageme/api/controllers"
	"github.com/codegangsta/negroni"
	"github.com/gorilla/mux"
)

//SetEmployeeRoutes sets route for employees
func SetEmployeeRoutes(router *mux.Router) *mux.Router {
	empRouter := mux.NewRouter()
	empRouter.HandleFunc("/api/v1/orgs/employees/add", controllers.AddEmployee).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/child/add", controllers.AddChildEmployee).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/", controllers.GetEmployees).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/org/{orgId}", controllers.GetEmployeessByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/employee/{empId}", controllers.GetEmployeesByMgr).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/departments/{deptId}", controllers.GetEmployeesByDept).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/branches/{branchId}", controllers.GetEmployeesByBranchMethods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/{id}", controllers.GetEmployee).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/users/{userId}", controllers.GetEmployeeByUser).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/edit/{id}", controllers.EditEmployeeByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/user/edit/{id}", controllers.EditEmployeeByUser).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/biodata/add", controllers.AddBiodataByEmp).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/pid/add", controllers.AddPIDByBio).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/health/detail/add", controllers.AddHealthDetByBio).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/work/experience/add", controllers.AddWorkExpByBio).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/education/add", controllers.AddEduByBio).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/biodatas/employees/{id}", controllers.GetBiosByEmp).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/biodatas/edit/{id}", controllers.GetBio).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/biodatas/employee/edit/{empId}", controllers.GetBioByEmp).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/biodatas/{id}", controllers.EditBioByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/biodatas/employee/{empId}", controllers.EditBioByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/pids/biodatas/{bioId}", controllers.GetPIDsByBio).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/pids/{id}", controllers.GetPID).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/pids/biodata/{bioId}", controllers.GetPIDByBio).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/pids/biodata/edit/{bioId}", controllers.EditPIDByBio).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/pids/edit/{id}", controllers.EditPIDByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/health/details/biodatas/{bioId}", controllers.GetHealthDetsByBio).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/health/details/{id}", controllers.GetHealthDetail).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/health/details/biodata/{bioId}", controllers.GetHealthDetailByBio).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/health/details/biodata/edit/{bioId}", controllers.EditHealthDetailByBio).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/health/details/edit/{id}", controllers.EditHealthDetailByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/work/experiences/biodatas/{bioId}", controllers.GetWorkExpsByBio).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/work/experiences/{id}", controllers.GetWorkExperience).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/work/experiences/biodata/{bioId}", controllers.GetWorkExperienceByBio).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/work/experiences/biodata/edit/{bioId}", controllers.EditWorkExperieceByBio).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/work/experiences/edit/{id}", controllers.EditWorkExperieceByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/educations/biodatas/{bioId}", controllers.GetEdusByBio).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/educations/{id}", controllers.GetEducation).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/educations/biodata/{bioId}", controllers.GetEduByBio).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/educations/biodata/edit/{bioId}", controllers.EditEduByBio).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/educations/{id}", controllers.EditEduByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/expense/claims/add", controllers.AddExpenseClaimByEmp).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/allocations/add", controllers.AddLeaveAllocationByEmp).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/applications/add", controllers.AddLeaveApplicationByEmp).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/blocklist/add", controllers.AddLeaveBlockListByOrg).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/holiday/list/add", controllers.AddHolidayListByEmp).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/appraisals/add", controllers.AddAppraisalByEmp).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/exit/add", controllers.AddExitByEmp).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/expense/claims/org/{orgId}", controllers.GetExpenseClaimsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/expense/claims/managers/{mgrId}", controllers.GetExpenseClaimsByMgr).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/expense/claims/employees/{empId}", controllers.GetExpenseClaimsByEmp).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/expense/claims/{id}", controllers.GetExpenseClaim).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/expense/claims/managers/edit/{mgrId}", controllers.EditExpenseClaimByMgr).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/expense/claims/employees/edit/{empId}", controllers.EditExpenseClaimByEmp).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/applications/orgs/{orgId}", controllers.GetLeaveApplicationsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/applications/managers/{mgrId}", controllers.GetLeaveApplicationsByMgr).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/applications/employees/{empId}", controllers.GetLeaveApplicationsByEmp).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/applications/{id}", controllers.GetLeaveApplication).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/applications/edit/{id}", controllers.EditLeaveApplicationByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/blocklists/orgs/{orgId}", controllers.GetLeaveBlockListsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/blocklists/{id}", controllers.GetLeaveBlockList).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/leave/blocklists/{id}", controllers.EditLeaveBlockListByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/holiday/lists/orgs/{orgId}", controllers.GetHolidayListsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/holiday/lists/{id}", controllers.GetHolidayList).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/holiday/lists/edit/{id}", controllers.EditHolidayListByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/appraisals/orgs/{orgId}", controllers.GetAppraisalsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/appraisals/managers/{mgrId}", controllers.GetAppraisalsByMgr).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/holiday/lists/edit/{id}", controllers.GetEditHolidayListByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/appraisals/edit/{id}", controllers.EditAppraisalByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/exits/orgs/{orgId}", controllers.GetExitsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/exits/managers/{mgrId}", controllers.GetExitsByMgr).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/exits/{id}", controllers.GetExit).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/exits/edit/{id}", controllers.EditExitByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/components/add", controllers.AddSalaryComponent).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/employees/add", controllers.AddSalaryEmployees).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/structures/add", controllers.AddSalaryStructure).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/types/add", controllers.AddActivityType).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/working/hour/add", controllers.AddWorkingHour).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/operation/add", controllers.AddOperation).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/workstation/add", controllers.AddWorkstation).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/timesheet/add", controllers.AddTimesheet).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/salaryslip/add", controllers.AddSalarySlip).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/cost/add", controllers.AddActivityCost).Methods("POST")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/components/org/{orgId}", controllers.GetSalaryComponentsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/employees/org/{orgId}", controllers.GetSalaryEmployeesByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/structures/org/{orgId}", controllers.GetSalaryStructuresByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/components/{id}", controllers.GetSalaryComponent).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/employees/{id}", controllers.GetSalaryEmployee).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/structures/{id}", controllers.GetSalaryStructure).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/components/edit/{id}", controllers.EditSalaryComponentByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/employees/edit/{id}", controllers.EditSalaryEmployeeByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/structures/edit/{id}", controllers.EditSalaryStructureByAdmin).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/structures/accounts/{acctId}", controllers.GetSalaryStructuresByAcct).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salary/structures/managers/{mgrId}", controllers.GetSalaryStructuresByMgr).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/types/org/{orgId}", controllers.GetActivityTypesByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/types/{id}", controllers.GetActivityType).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/types/edit/{id}", controllers.EditActivityTypeByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/operations/org/{orgId}", controllers.GetOperationsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/operations/{id}", controllers.GetOperation).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/operations/edit/{id}", controllers.EditOperationByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/working/hours/org/{orgId}", controllers.GetWorkingHoursByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/working/hours/{id}", controllers.GetworkingHour).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/working/hours/edit/{id}", controllers.EditWorkingHourByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/workstations/org/{orgId}", controllers.GetWorkstationsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/workstations/{id}", controllers.GetWorkstation).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/workstations/edit/{id}", controllers.EditWorkstationByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/timesheets/org/{orgId}", controllers.GettTimesheetsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/timesheets/employees/{empId}", controllers.GettTimesheetsByEmp).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/timesheets/managers/{mgrId}", controllers.GettTimesheetsByMgr).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/timesheets/{id}", controllers.GetTimesheet).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/timesheets/edit/{id}", controllers.EditTimesheetByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/salaryslips/org/{orgId}", controllers.GetSalarySlipsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salaryslips/managers/{mgrId}", controllers.GetSalarySlipsByMgr).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salaryslips/employees/{empId}", controllers.GetSalarySlipsByEmp).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salaryslips/{id}", controllers.GetSalarySlip).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/salaryslips/edit/{id}", controllers.EditSalarySlipByAdmin).Methods("PUT")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/costs/org/{orgId}", controllers.GetActivityCostsByOrg).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/costs/type/{typeId}", controllers.GetActivityCostsByType).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/costs/employees/{empId}", controllers.GetActivityCostsByEmp).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/costs/{id}", controllers.GetActivityCost).Methods("GET")
	empRouter.HandleFunc("/api/v1/orgs/employees/activity/costs/edit/{id}", controllers.EditActivityCostByAdmin).Methods("PUT")
	router.PathPrefix("/api/v1/admin/org/employees/").Handler(negroni.New(
		negroni.HandlerFunc(common.Authorize),
		negroni.Wrap(empRouter),
	))
	return router
}
